name: cicd

on:
  push:
    paths: 
      - src/**
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get Hash
        shell: bash
        run: |
         echo "COMMIT_ID=${GITHUB_SHA::6}" >> "$GITHUB_ENV"

      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: devir2/python-app:${{ env.COMMIT_ID }}
  cd:
    runs-on: self-hosted
    needs: ci
    steps:
    
      -
        name: install argocd
        shell: bash
        run: |
          curl -sSL -o argocd-linux-amd64 https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          sudo install -m 555 argocd-linux-amd64 /usr/local/bin/argocd
      - 
        name: Argocd sync
        shell: bash
        run: |
         argocd login argocd-server.argocd \
         --insecure \
         --grpc-web \
         --username admin \
         --password {{ secrets.ARGOCD_PASWORD }}
         argocd app sync python-app
         


